print('Please enter the following')
print()
adjective = input('adjective' )
animal = input('animal' )
verb1 = input('verb1' )
exclamation = input('exclamation' )
verb2 = input('verb2' )
verb3 = input('verb3' )

print('Your story is:')
print()
print('The other day, I was really in trouble. It all started when I saw a very[adjective] [animal] [verb] down the hallway. [exclamation]! I yelled. But all I could think to do was to [verb2] over and over. Miraculously,that caused it to stop, but not before it tried to [verb3] right in front of my family.)
